import { AppItem, FileItem, ThreatItem, SystemStats } from '../types/scanner';

export const INITIAL_SYSTEM_STATS: SystemStats = {
  protectionScore: 98,
  isProtected: true,
  lastScanTimestamp: 'Today, 09:42 AM',
  ramUsagePercent: 62,
  storageUsagePercent: 74,
  batteryTempCelsius: 32.4,
  virusDefinitionsVersion: 'v2.0.1420-2026.08.25',
  realtimeProtectionEnabled: true,
  cloudScanningEnabled: true,
  wifiSecurityEnabled: true,
  autoUpdateEnabled: true,
};

export const MOCK_APPS: AppItem[] = [
  {
    id: 'app-1',
    name: 'Secure Vault Pro',
    packageName: 'com.akn.security.vault',
    version: '3.4.1',
    icon: 'shield-checkmark',
    sizeMb: 24.5,
    permissions: ['READ_EXTERNAL_STORAGE', 'BIOMETRIC', 'USE_FINGERPRINT'],
    riskLevel: 'safe',
    category: 'Utility',
    installedDate: '2026-05-12',
    sha256: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
  },
  {
    id: 'app-2',
    name: 'FlashLight Lite & Torch',
    packageName: 'com.quicktool.flashy.app',
    version: '1.0.8',
    icon: 'flash',
    sizeMb: 8.2,
    permissions: ['CAMERA', 'READ_CONTACTS', 'SEND_SMS', 'ACCESS_FINE_LOCATION', 'BACKGROUND_PROCESS'],
    riskLevel: 'danger',
    category: 'Utility',
    installedDate: '2026-08-20',
    sha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    threatName: 'Android.Trojan.SpySMS.AKN',
    description: 'Suspicious app requesting SMS & Location access despite being a simple flashlight tool.',
  },
  {
    id: 'app-3',
    name: 'Global Crypto Wallet',
    packageName: 'com.cryptopay.global',
    version: '5.12.0',
    icon: 'wallet',
    sizeMb: 42.1,
    permissions: ['INTERNET', 'CAMERA', 'BIOMETRIC', 'USE_CREDENTIALS'],
    riskLevel: 'safe',
    category: 'Finance',
    installedDate: '2026-01-15',
    sha256: 'a591a6d40bf420404a011733cfb7b190d62c65bf0bcda32b57b277d9ad9f146e',
  },
  {
    id: 'app-4',
    name: 'Free Game Booster Turbo',
    packageName: 'com.booster.game.speedup',
    version: '2.1.0',
    icon: 'game-controller',
    sizeMb: 18.9,
    permissions: ['SYSTEM_ALERT_WINDOW', 'GET_TASKS', 'WRITE_SETTINGS'],
    riskLevel: 'warning',
    category: 'Game',
    installedDate: '2026-07-04',
    sha256: '7d57aaea122e232e02a1ef24279b94de69493922d0577a7d4d4202476d05f32a',
    threatName: 'Adware.PUP.Tracker.Boost',
    description: 'Aggressive ad overlay injector running background system window tasks.',
  },
  {
    id: 'app-5',
    name: 'Social Connect',
    packageName: 'com.social.connect.chat',
    version: '12.8.4',
    icon: 'chatbubbles',
    sizeMb: 68.3,
    permissions: ['INTERNET', 'CAMERA', 'RECORD_AUDIO', 'READ_CONTACTS'],
    riskLevel: 'safe',
    category: 'Social',
    installedDate: '2026-03-01',
    sha256: '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b',
  },
  {
    id: 'app-6',
    name: 'PDF Reader & Scanner Pro',
    packageName: 'com.docscan.pdf.reader',
    version: '4.0.2',
    icon: 'document-text',
    sizeMb: 31.0,
    permissions: ['READ_EXTERNAL_STORAGE', 'WRITE_EXTERNAL_STORAGE', 'CAMERA'],
    riskLevel: 'safe',
    category: 'Productivity',
    installedDate: '2026-04-18',
    sha256: 'd4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35',
  },
  {
    id: 'app-7',
    name: 'Android System Webview',
    packageName: 'com.google.android.webview',
    version: '128.0.6613',
    icon: 'cog',
    sizeMb: 112.0,
    permissions: ['INTERNET'],
    riskLevel: 'safe',
    category: 'System',
    installedDate: '2026-01-01',
    sha256: '4e07408562bedb8b60ce05c1decfe3ad16b72230967de01f640b7e4729b49fce',
  },
];

export const MOCK_FILES: FileItem[] = [
  {
    id: 'file-1',
    name: 'Invoice_Payment_Aug2026.pdf.exe',
    path: '/sdcard/Download/Invoice_Payment_Aug2026.pdf.exe',
    extension: '.exe',
    sizeKb: 1420,
    modifiedDate: '2026-08-24 16:30',
    riskLevel: 'danger',
    type: 'executable',
    threatName: 'Win32.Dropper.RansomAKN',
    hash: '8f4e09a32c66d10115e6123490abcde8',
  },
  {
    id: 'file-2',
    name: 'Modded_Game_Unlimited_Coins.apk',
    path: '/sdcard/Download/Modded_Game_Unlimited_Coins.apk',
    extension: '.apk',
    sizeKb: 45200,
    modifiedDate: '2026-08-22 11:15',
    riskLevel: 'warning',
    type: 'apk',
    threatName: 'Android.Riskware.FakeInstall',
    hash: '7c9e01a88b56f21225d7345681123456',
  },
  {
    id: 'file-3',
    name: 'Project_Report_Q3_Final.docx',
    path: '/sdcard/Documents/Project_Report_Q3_Final.docx',
    extension: '.docx',
    sizeKb: 2840,
    modifiedDate: '2026-08-25 10:00',
    riskLevel: 'safe',
    type: 'document',
    hash: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d',
  },
  {
    id: 'file-4',
    name: 'Backup_Database_2026.zip',
    path: '/sdcard/Backups/Backup_Database_2026.zip',
    extension: '.zip',
    sizeKb: 128500,
    modifiedDate: '2026-08-10 14:22',
    riskLevel: 'safe',
    type: 'archive',
    hash: '9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b',
  },
  {
    id: 'file-5',
    name: 'system_update_patch.sh',
    path: '/sdcard/Download/system_update_patch.sh',
    extension: '.sh',
    sizeKb: 14,
    modifiedDate: '2026-08-23 22:05',
    riskLevel: 'warning',
    type: 'script',
    threatName: 'Shell.Exploit.RootElevate',
    hash: '5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c',
  },
];

export const MOCK_THREATS: ThreatItem[] = [
  {
    id: 'threat-1',
    title: 'Trojan SMS Interceptor',
    targetName: 'FlashLight Lite & Torch',
    targetPath: 'com.quicktool.flashy.app',
    targetType: 'app',
    riskLevel: 'danger',
    threatName: 'Android.Trojan.SpySMS.AKN',
    threatCategory: 'Trojan',
    description: 'Intercepts incoming security verification SMS codes and sends them to unauthorized command servers.',
    recommendation: 'Immediate Uninstall Recommended',
    status: 'active',
  },
  {
    id: 'threat-2',
    title: 'Disguised Executable Ransomware',
    targetName: 'Invoice_Payment_Aug2026.pdf.exe',
    targetPath: '/sdcard/Download/Invoice_Payment_Aug2026.pdf.exe',
    targetType: 'file',
    riskLevel: 'danger',
    threatName: 'Win32.Dropper.RansomAKN',
    threatCategory: 'Ransomware',
    description: 'Double extension trick disguising malicious Windows executable payload as a PDF document.',
    recommendation: 'Delete File immediately',
    status: 'active',
  },
];

export const SCAN_STEPS = [
  'Initializing signature engine & definitions v2.0...',
  'Checking bootloader integrity & system partitions...',
  'Analyzing installed application signatures...',
  'Scanning application permissions & background receivers...',
  'Inspecting storage downloads & high-risk directories...',
  'Running heuristic AI malware pattern match...',
  'Finalizing security analysis report...',
];
